name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: prod
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              arch_name: x86_64-linux-gnu
              c_compiler: gcc
              cpp_compiler: g++
              cc: gcc
          - pair:
              arch_name: aarch64-linux-gnu
              c_compiler: gcc-aarch64-linux-gnu
              cpp_compiler: g++-aarch64-linux-gnu
              cc: aarch64-linux-gnu-gcc
          - pair:
              arch_name: arm-linux-gnueabihf
              c_compiler: gcc-arm-linux-gnueabihf
              cpp_compiler: g++-arm-linux-gnueabihf
              cc: /usr/bin/arm-linux-gnueabihf-gcc-9
          - pair:
              arch_name: riscv64-linux-gnu
              c_compiler: gcc-riscv64-linux-gnu
              cpp_compiler: g++-riscv64-linux-gnu
              cc: /usr/bin/riscv64-linux-gnu-gcc
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.3
          elixir-version: 1.13.4
      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.pair.c_compiler }} ${{ matrix.pair.cpp_compiler }}
      - name: Compile
        run: |
          mkdir -p artefacts
          mix deps.get
          export CC=${{ matrix.pair.cc }}
          mix do escript.build
          mv priv/debug.so artefacts/debug-${{ matrix.pair.arch_name }}-${GITHUB_REF##*/v}.so

      - uses: softprops/action-gh-release@v1
        with:
          files: artefacts/*.so

  macos:
    runs-on: macos-11
    env:
      MIX_ENV: prod
    steps:
      - uses: actions/checkout@v3
      - name: macOS setup
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force
      - name: Compile
        run: |
          mkdir -p artefacts
          export CC="gcc -arch x86_64"
          mix deps.get
          mix compile
          mv priv/debug.so artefacts/debug-x86_64-apple-darwin-${GITHUB_REF##*/v}.so
          rm -rf priv && rm -rf _build && rm -f debug_nif
          export CC="gcc -arch arm64"
          mix compile
          mv priv/debug.so artefacts/debug-aarch64-apple-darwin-${GITHUB_REF##*/v}.so

      - uses: softprops/action-gh-release@v1
        with:
          files: artefacts/*.so
